export const dataProvider = [
    { snippet: 'snippet1.php', unused: 4 },
    { snippet: 'snippet2.php', unused: 1 },
    { snippet: 'snippet3.php', unused: 0 },
    { snippet: 'snippet4.php', unused: 5 },
    { snippet: 'snippet5.php', unused: 5 },
    { snippet: 'snippet6.php', unused: 0 },
    { snippet: 'snippet7.php', unused: 1 },
    { snippet: 'snippet8.php', unused: 0 },
    { snippet: 'snippet9.php', unused: 0 },
    { snippet: 'snippet10.php', unused: 1 },
    { snippet: 'snippet11.php', unused: 2 },
    { snippet: 'snippet12.php', unused: 1 },
    { snippet: 'snippet13.php', unused: 1 },
    { snippet: 'snippet14.php', unused: 3 },
    { snippet: 'snippet15.php', unused: 0 },
    { snippet: 'snippet16.php', unused: 0 },
    { snippet: 'snippet18.php', unused: 0 },
    { snippet: 'snippet19.php', unused: 1 },
    { snippet: 'snippet20.php', unused: 0 },
    { snippet: 'snippet21.php', unused: 1 },
    { snippet: 'snippet22.php', unused: 0 },
    { snippet: 'snippet23.php', unused: 3 },
    { snippet: 'snippet24.php', unused: 1 },
    { snippet: 'snippet25.php', unused: 2 },
    { snippet: 'snippet26.php', unused: 3 },
    { snippet: 'snippet27.php', unused: 0 },
    { snippet: 'snippet28.php', unused: 0 },
    { snippet: 'snippet29.php', unused: 1 },
    { snippet: 'snippet30.php', unused: 1 },
    { snippet: 'snippet31.php', unused: 0 },
    { snippet: 'snippet32.php', unused: 0 },
    { snippet: 'snippet33.php', unused: 1 },
    { snippet: 'snippet34.php', unused: 0 },
    { snippet: 'snippet35.php', unused: 1 },
]

export const invalidPhpSyntaxDataProvider = [
    { snippet: 'snippet17.php', unused: 0 },
]