name: Node CI

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: main

env:
  CI: true
  DISPLAY: ':99.0'
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
  COVERALLS_GIT_BRANCH: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set Environment Variables
      uses: tw3lveparsecs/github-actions-setvars@v0.2
      with:
        envFilePath: ./envvars.for.actions

    - name: Use Node.js
      uses: actions/setup-node@v7
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: export display
      run: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo ">>> Started xvfb"

    - name: npm install
      run: |
        npm install

    - name: npm build
      run: |
        npm run vscode:prepublish

    - name: npm test
      run: |
        npm run test:integration

    - name: npm coverage
      if: github.ref == 'refs/heads/main'
      run: |
        npm run coveralls

    - name: npm package standalone extension
      if: github.ref == 'refs/heads/main'
      run: |
        npm i -g vsce
        npm run package

    - name: store artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v6
      with:
        name: php-import-checker-vscode-extension
        path: ./*.vsix

  dependabot:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
      repository-projects: read

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          skip-commit-verification: true

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Approve a PR if not already approved
        run: |
          gh pr checkout "$PR_URL"
            if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved.";
          fi
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Enable auto-merge for Dependabot PRs
        if: ${{ contains(github.event.pull_request.title, 'bump')}}
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
